# Python CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-v2-{{ checksum "scripts/requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - save_cache:
          key: test-dependencies-v2-{{ checksum "scripts/requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Check data
          command: |
            . venv/bin/activate
            python3 scripts/check_data.py
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r scripts/requirements.txt
      - save_cache:
          key: test-dependencies-v1-{{ checksum "scripts/requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Build data
          command: |
            . venv/bin/activate
            python3 scripts/build_data.py
      - persist_to_workspace:
          root: ~/repo
          paths:
            - _site
  deploy_staging:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "12:df:37:a8:2a:c2:07:6d:64:8a:d9:3e:f4:5f:ae:04"
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/circleci/deploy_staging.sh
  deploy_prod:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          finterprints:
            - "a7:bc:ca:31:05:e3:2f:cf:3f:37:da:4f:c3:22:73:47"
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Deploy to production Github
          command: bash scripts/deploy/circleci/deploy_prod.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master
